### PR TITLE
DAOS-16752 mercury: update to mercury 2.4.0

### PR DESCRIPTION
**Pull request by soumagne**
Update required libfabric version (>= 1.20)

PR-repos: libfabric@PR-77:lastBuild

### CODE REVIEW

**Review by brianjmurrell — COMMENTED** [review]
Changes LGTM.  Are the downstream testing failures known issues?

**Comment by soumagne** [comment]
Yes every single dependency PR (libfabric / spdk / etc) is failing because of https://daosio.atlassian.net/browse/DAOS-16732

**Comment by brianjmurrell** [comment]
> Yes every single dependency PR (libfabric / spdk / etc) is failing because of [daosio.atlassian.net/browse/DAOS-16732](https://daosio.atlassian.net/browse/DAOS-16732)

Ahhh.  Same issue/solution as discussed in the [libfabric PR comment](https://github.com/daos-stack/libfabric/pull/77#issuecomment-2441858830) then.

**Review by brianjmurrell — APPROVED** [review]

**Review by phender — APPROVED** [review]

**Review by jgmoore-or — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]

**Comment by phender** [comment]
master branch testing passed in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15413/4/ for https://github.com/daos-stack/daos/pull/15413.

release/2.6 branch testing passed in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-15443/2/ for https://github.com/daos-stack/daos/pull/15443

**Pull request merged**
