### PR TITLE
DAOS-10403 mercury: Turn off unified mode.

### PR DESCRIPTION
**Pull request by jgmoore-or**
Signed-off-by: Joseph Moore <joseph.moore@intel.com>

### CODE REVIEW

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
This PR seems to only be adding a `%changelog` entry with no other meaningful change.  Surely there must be something else that changes to reflect what the `%changelog` entry is saying is changing.

**Comment by jgmoore-or** [comment]
The PR makes a one-line change to the existing UCX patch file to change the mode for unified to disabled.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
You are missing the update of the `Release:` in the `mercury.spec`.

**Comment by jgmoore-or** [comment]
Changelog has been corrected in mercury.spec.

**Review by frostedcmos — APPROVED** [review]

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
@brianjmurrell any objections? Are we good to land?

**Comment by brianjmurrell** [comment]
> @brianjmurrell any objections? Are we good to land?

No.  It failed testing.  The following suggestion from Skype was not applied:

> Conversation with Joseph Moore on Thu 28 Apr 2022 11:36:59 AM:
> ...
> (02:38:28 PM) Brian J. Murrell: you can actually work-around your issue and get the tests on the PR running so that it looks successful by adding "'rpmlint_rpms_allow_errors': true" to the arguments to packageBuildingPipelineDAOS() in Jenkinsfile, like this: https://github.com/daos-stack/mercury/blob/b4b7185a0b16203d753353c32908cd64bc11c3fd/Jenkinsfile#L43-L45

I should have resisted making the suggestion OOB in Skype and made it here in the PR instead.

I have just landed #77 which takes care of this however.  This PR just needs to merge mercury@master.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
Needs a mercury@master merge.

**Review by frostedcmos — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Please add @daos-stack/release-engineering as a reviewer when ready for landing.  We do this to ensure a dependency is not landed prematurely and possibly breaking CI for all of the PRs in progress.  Hopefully at some point in the future we can automate more of the manual testing that goes into making sure that CI does not get broken and this becomes less necessary.

**Pull request merged**
